config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
    post 'create_comment', on: :member
  end

  root "posts#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :name, presence: true
  validates :body, presence: true, length: { minimum: 10, message: "must be at least 10 characters long" }
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true
    validates :body, presence: true,
                    length: { minimum: 10, message: "must be at least 10 characters long" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  
  def new
    @comment = Comment.new
  end
  
  def create
    @comment = @post.comments.build(comment_params)

    if @comment.save
      redirect_to post_path(@post), notice: 'Comment posted.'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @comment
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post), notice: 'Comment updated.'
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post), notice: 'Comment was successfully deleted.'
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end
  

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment], local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div style='color: red'>
      <h2><%= pluralize(@comment.errors.count, 'error') %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <section class='form-proper'>
  <div class = 'form-input'>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name , class:'input' %>
  </div>

  <div class = 'form-input'>
    <%= form.label :body, style: 'display: block' %>
    <%= form.text_area :body, class:'comment-input' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  </section>
<% end %>

app/views/comments/edit.html.erb
<div class='wrapper'>
<h1 class='page-title'>Edit Comment</h1>
<%= link_to 'Back to Post', post_path(@post), class:'link' %>
</div>

<%= render 'form', post: @post, comment: @comment %>

app/views/comments/new.html.erb
<div class='wrapper'>
<h1 class='page-title'>New Comment</h1>
<%= link_to 'Back to Post', post_path(@post), class:'link' %>
</div>

<%= render 'form', post: @post, comment: @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style='color: red'>
      <h2><%= pluralize(post.errors.count, 'error') %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <section class='form-proper'>
  <div class = 'form-input'>
    <%= form.label :title, style: 'display: block' %>
    <%= form.text_field :title , class:'input' %>
  </div>

  <div class = 'form-input'>
    <%= form.label :body, style: 'display: block' %>
    <%= form.text_area :body, class:'text-input' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  </section>
<% end %>

app/views/posts/_post.html.erb
<div id='<%= dom_id post %>' class='post-page'>
 <div class='post-upper'>
  <div class='center-title'>
    <strong class='page-title'><%= post.title %></strong>
  </div>

  <div class='time'>
    <% if post.persisted? %>
      <div class='form-input'>
        <strong>Posted At:</strong> <%= post.created_at %>
      </div>
    <% end %>
    <% if post.updated_at? %>
      <div class='form-input'>
        <strong>Updated At:</strong> <%= post.updated_at %>
      </div>
    <% end %> 
  </div>
 </div>

  <div class ='post-content'>
    <%= simple_format(@post.body) %>
  </div>

</div>

app/views/posts/edit.html.erb
<div class='wrapper'>
  <h1 class='page-title'>Edit Post</h1>
  <div>
    <%= link_to 'Back to Post', @post , class: 'link' %> |
    <%= link_to 'Home', posts_path, class: 'link' %> 
  </div>
</div>


<%= render 'form', post: @post %>

<br>

app/views/posts/index.html.erb
<div class='home'>
    <div class='page_label'>
      <h1 class='page-title'>Rails Blog</h1>
      <p class='subtitle'>This is a simple blog page made with Rails. It allows you to post articles, and other people can comment on it.</p>
      <%= link_to "New post", new_post_path, class: 'link-button' %>
    </div>
    <div class='notice-container'>
      <p style='color: red'><%= notice %></p>
    </div>



<div id='posts'>
  <% @posts.each do |post| %>
    <div id="<%= dom_id post %>" class='indiv-post'>
      <p class='title-wrapper'>
        <strong class='post-title'>
          <%= post.title %>
        </strong>
      </p>

    <div class='time'>
    <% if post.persisted? %>
      <div class='form-input'>
        <strong>Posted At:</strong> <%= post.created_at %>
      </div>
    <% end %>
    <% if post.updated_at? %>
      <div class='form-input'>
        <strong>Updated At:</strong> <%= post.updated_at %>
      </div>
    <% end %> 
  </div>

      <p class='post-body'>
        <%= truncate(post.body, length: 150) %>
      </p>

      <p>
        <%= link_to 'Read more', post , class:'link' %>
      </p>
    </div>
  <% end %>
</div>


</div>

app/views/posts/new.html.erb
<div class='wrapper'>
  <h1 class='page-title'>New post</h1>
  <%= link_to 'HOME', posts_path, class: 'link-button' %>
</div>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class='message-container'>
<% flash.each do |key, value| %>
  <p class="<%= key %>"><%= value %></p>
<% end %>
</div>

<%= render @post %>

<div class='post-actions'>
  <div class ='top-link'>
  <%= link_to 'Edit Post', edit_post_path(@post), class:'link' %> |
  <%= link_to 'Home', posts_path, class:'link'%>
  </div>
  <%= button_to 'Delete', @post, method: :delete, class:'delete-btn' %>
</div>

<div class='comment-form'>
    <%= link_to "Leave a message", new_post_comment_path(@post), class: 'link-button' %>

    
</div>

<div class='comments-section'>
  <h2><%= @post.comments.count %> Comment/s:</h2>
  <% @comments.each do |comment| %>
    <div class='comment'>
      <h4 class='comment-name'><%= comment.name %></h4>
      
      <div class='time'>
         <% if comment.persisted? %>
          <div class='form-input'>
            <strong>Posted At:</strong> <%= comment.created_at %>
          </div>
        <% end %>
        <% if comment.updated_at? %>
          <div class='form-input'>
            <strong>Updated At:</strong> <%= comment.updated_at %>
          </div>
        <% end %> 
      </div>

      <p class='comment-body'><%= comment.body %></p>
      <div class='bottom-row'>
        <%= button_to link_to 'Edit', edit_post_comment_path(@post, comment) , class: 'edit-comment' %>  |
        <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete, class: 'delete-comment' %>
      </div>
    </div>
  <% end %>
</div>